name: Generate xml sitemap
on:
  workflow_dispatch:
  push:
    branches:
        - main
permissions:
    contents: write
jobs:
    sitemap_job:
        name: Generate a sitemap
        if: ${{ !github.event.repository.is_template }}
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout the repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 
            
        - name: Generate the sitemap
          id: sitemap
          uses: cicirello/generate-sitemap@v1
          with:
            base-url-path: https://yjian012.github.io/Yi-blog/
            path-to-root: gh-pages
            additional-extensions: md
            
        - name: Output stats
          run: |
            echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
            echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
            echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"